from __future__ import annotations

import argparse
import sys
from pathlib import Path

from relion_pipeline_visualizer.parser import parse_pipeline
from relion_pipeline_visualizer.graph import get_full_graph, get_subgraph
from relion_pipeline_visualizer.mermaid import render_mermaid


def _render_svg(mermaid_text: str, svg_path: Path) -> None:
    """Render Mermaid text to SVG using the mmdc Python package."""
    try:
        from mmdc import MermaidConverter

        converter = MermaidConverter()
        converter.to_svg(mermaid_text, output_file=svg_path)
    except ImportError:
        print(
            "Warning: 'mmdc' package not installed. Skipping SVG generation.\n"
            "  Install it with: pip install mmdc",
            file=sys.stderr,
        )
    except Exception as e:
        print(f"Warning: SVG generation failed: {e}", file=sys.stderr)


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(
        description="Visualize a RELION pipeline STAR file as a Mermaid diagram.",
    )
    parser.add_argument("star_file", help="Path to default_pipeline.star")
    parser.add_argument("--job", help="Focus on a specific job (e.g. 'Refine3D/job058/')")
    parser.add_argument(
        "--upstream",
        action="store_true",
        help="Include upstream ancestors (default when --job is given)",
    )
    parser.add_argument(
        "--downstream",
        action="store_true",
        help="Include downstream descendants",
    )
    parser.add_argument(
        "--output", "-o",
        help="Output path for .mmd file (default: same directory as star_file)",
    )
    parser.add_argument(
        "--no-svg",
        action="store_true",
        help="Skip SVG generation (SVG is generated by default)",
    )

    args = parser.parse_args(argv)
    pipeline = parse_pipeline(args.star_file)

    if args.job:
        job_name = args.job
        if job_name not in pipeline.jobs:
            print(f"Error: job '{job_name}' not found in pipeline.", file=sys.stderr)
            print("Available jobs:", file=sys.stderr)
            for name in sorted(pipeline.jobs):
                print(f"  {name}", file=sys.stderr)
            sys.exit(1)

        upstream = args.upstream
        downstream = args.downstream
        # Default to upstream if neither flag given
        if not upstream and not downstream:
            upstream = True

        jobs, edges = get_subgraph(pipeline, job_name, upstream=upstream, downstream=downstream)
    else:
        jobs, edges = get_full_graph(pipeline)

    mermaid_text = render_mermaid(jobs, edges, pipeline)

    # Determine output path
    star_path = Path(args.star_file)
    if args.output:
        mmd_path = Path(args.output)
    else:
        mmd_path = star_path.parent / "pipeline.mmd"

    # Write .mmd file
    mmd_path.write_text(mermaid_text)
    print(f"Wrote Mermaid diagram to {mmd_path}", file=sys.stderr)

    # Write .svg file
    if not args.no_svg:
        svg_path = mmd_path.with_suffix(".svg")
        _render_svg(mermaid_text, svg_path)
        if svg_path.exists():
            print(f"Wrote SVG diagram to {svg_path}", file=sys.stderr)
